#!/usr/bin/env python3
"""Refresh the local eBay credential cache from 1Password.

Pulls EBAY_APP_ID and EBAY_CERT_ID from `op` once (one Touch ID prompt per
field) and writes them to ~/.config/mac-bid-claude/ebay.env with mode 0600.
Subsequent `scripts/ebay_search.py` runs source the cache instead of calling
`op read`, eliminating the per-call biometric prompt.

Re-run this script when eBay rotates the API keys.
"""

import os
import stat
import subprocess
import sys

OP_PATH_APP_ID = "op://Personal/za7ym3agvpwbszokahxsfr5sq4/username"
OP_PATH_CERT_ID = "op://Personal/za7ym3agvpwbszokahxsfr5sq4/credential"

CRED_CACHE_FILE = os.path.expanduser("~/.config/mac-bid-claude/ebay.env")


def op_read(path):
    try:
        r = subprocess.run(
            ["op", "read", path], capture_output=True, text=True, timeout=30
        )
    except FileNotFoundError:
        sys.exit("error: `op` CLI not found on PATH")
    except subprocess.TimeoutExpired:
        sys.exit(f"error: `op read {path}` timed out (30s)")
    if r.returncode != 0:
        msg = (r.stderr or "").strip() or f"exit {r.returncode}"
        sys.exit(f"error: `op read {path}` failed: {msg}")
    return r.stdout.strip()


def main():
    print(f"Reading {OP_PATH_APP_ID} ...", file=sys.stderr)
    app_id = op_read(OP_PATH_APP_ID)
    print(f"Reading {OP_PATH_CERT_ID} ...", file=sys.stderr)
    cert_id = op_read(OP_PATH_CERT_ID)

    if not app_id or not cert_id:
        sys.exit("error: 1Password returned an empty value for one of the fields")

    os.makedirs(os.path.dirname(CRED_CACHE_FILE), exist_ok=True)
    tmp = CRED_CACHE_FILE + ".tmp"
    with open(tmp, "w") as f:
        f.write("# Generated by scripts/refresh_ebay_credentials.py\n")
        f.write("# Re-run that script after eBay rotates the keys.\n")
        f.write(f"EBAY_APP_ID={app_id}\n")
        f.write(f"EBAY_CERT_ID={cert_id}\n")
    os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)  # 0600
    os.replace(tmp, CRED_CACHE_FILE)

    print(f"Wrote {CRED_CACHE_FILE} (mode 0600)", file=sys.stderr)


if __name__ == "__main__":
    main()
